version: "3.2"
services:

  redis: # rename to redis_server
    image: "redis:alpine"

    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

  web:
    image: conreg0.azurecr.io/blackops
    build: .
    ports:
      - "7846:7846"
      - "5555:5555"

