version: "3.2"
services:

  web:
    image: com.blackops
    build: .
    ports:
      - "7846:7846"
      - "5555:5555"

  redis:
    image: "redis:alpine"

    command: redis-server 

    ports:
      - "6379:6379"

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
