# version: "3.2"
# services:

#   # redis_server:
#   #   image: "redis:alpine"
#   #   container_name: redis
#   #   command: ["redis-server", "--bind", "127.0.0.1", "--port", "6379"]

#   #   ports:
#   #     - "6379:6379"

#   #   volumes:
#   #     - $PWD/redis-data:/var/lib/redis
#   #     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

#   web:
#     image: conreg0.azurecr.io/blackops
#     build: .
#     ports:
#       - "80:80"

#     # environment:
#     #   REDIS_HOST: redis_server


version: "3.2"
services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      DEBUG: ${DEBUG}
      BTCTURK_PUBLIC_KEY_PROD: ${BTCTURK_PUBLIC_KEY_PROD} 
      BTCTURK_PRIVATE_KEY_PROD: ${BTCTURK_PRIVATE_KEY_PROD}

  redis_server:
    image: "redis:alpine"
    restart: always
